# Generated by Django 2.1.2 on 2018-12-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kep',
            field=models.ImageField(default='cdefault.png', upload_to='post_pics'),
        ),
    ]
