# Generated by Django 2.1.2 on 2018-12-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_kep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='kep',
        ),
    ]
