# Generated by Django 2.1.2 on 2018-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181218_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='kep',
            field=models.ImageField(default='pdefault.png', upload_to='post_pics'),
        ),
    ]
